name: Sync

on:
  schedule:
  - cron: "0 0 */3 * *"

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 12.x
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - name: Yarn install and quality check
      run: |
        yarn install --frozen-lockfile
        yarn build
      env:
        CI: true
    - name: Sync
      run: |
        node dist/main.js
      env:
        CI: true
